//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeagueMVCProject.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Players
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> TeamsId { get; set; }
        public Nullable<int> Number { get; set; }
        public string PositionName { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> LeagueId { get; set; }
    
        public virtual Leagues Leagues { get; set; }
        public virtual Teams Teams { get; set; }
    }
}
